### ISSUE TITLE
Bug: Setting page shows Different Account

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/push-notification#20]
If a user goes to the settings page, he gets information from a different account.
Reference: https://secure.helpscout.net/conversation/1438586973/182759

**Comment by digitalsetups** [comment]
Yes, this is happening with all new sign ups as well. 

When you register, you get someone else account logged in. In my case, I got access to ahmed@magazine3.com (sorry, Ahmed Kaludi :| ) and some others randomly on settings page. 

It's like on each page, a different account is being pulled. 


PLUS, just because of this, many users are using SAME or OTHER account tokens. They're getting push notifications from other accounts.

**Comment by kumawatvikas** [comment]
@HaripriyaHari  we have checked and fixed the things in new updates, if you have still any issue please let us know.
