### ISSUE TITLE
The Select All Categories check box is not visible in the backend, but it is visible in the front end.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/push-notification#43]
We cannot see Select ALL options in the backend, but we can see Select ALL options on the front end. So we need to create a Select ALL option in the backend so the user can turn it off if he doesn't need it.

Ref screenshot of the Backend. https://prnt.sc/_XswjVbQsNX3

Ref screenshot of the friend end. https://prnt.sc/p94gW9ObRlEx

Ref ticket: https://magazine3.in/conversation/22720?folder_id=29

**Comment by akshaywali** [comment]
ALL option in frontend is added dynamically for the UX since user have to check only one checkbox instead of multiple checkboxes. The issue which user is facing is he is unable to translate "ALL" string into desired language.
 User can use the following WPML documentation for translation of the string.
 https://wpml.org/documentation/getting-started-guide/string-translation/finding-strings-that-dont-appear-on-the-string-translation-page/#strings-arent-selected-for-translation

**Comment by akshaywali** [comment]
Added "ALL" string to translation , now it can be easily translated into any language

**Comment by akshaywali** [comment]
update pushed in 1.26 version
